name: Keep Supabase Alive

on:
  schedule:
    # Berjalan setiap hari Senin & Kamis jam 00:00 UTC
    - cron: "0 0 * * 1,4"
  workflow_dispatch: # Agar bisa dites manual lewat tab Actions GitHub

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Rest API
        run: |
          curl -i -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}"
